### ISSUE TITLE
pod update some framework not working

### ISSUE THREAD

**Issue by CodeEagle** [leavez/cocoapods-binary#83] opened 2019-07-09 03:53 UTC
Reproduce
first add `pod 'SomePod'`
pod install

and then update that pod 
update podfile  `pod 'SomePod', :git=>'....', :branch=>'master'`
then `pod update SomePod --no-repo-update`

will only update source file but not building framework

**Comment by tivadargyorgy** [comment] 2019-07-10 09:06
Hi @CodeEagle, could you provide the specific podfile and pod install output? (Pls run the pod install verbose mode)

**Comment by CodeEagle** [comment] 2019-07-10 09:09
nope, just check out the step above

**Comment by tivadargyorgy** [comment] 2019-07-10 09:17
Unfortunately, it's not enough for me to investigate it.

**Comment by CodeEagle** [comment] 2019-07-10 09:23
em, Unfortunately

**Comment by AdiAyyakad** [comment] 2019-07-10 20:09
I'm seeing this issue trying update from RxSwift ~4 to RxSwift 5

**Comment by tuantm-citigo** [comment] 2019-09-19 10:44
### Podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Cocoapods binary
plugin 'cocoapods-binary'

# Keep source code for backing up
keep_source_code_for_prebuilt_frameworks!

# Enable bitcode
enable_bitcode_for_prebuilt_frameworks!

# Apply prebuilt for all pods
all_binary!

target 'cocoapods-binary-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoapods-binary-example
  pod 'AFNetworking'

end
```

### Environment
```
- Cocoapods: 1.7.5
- Cocoapods-binary: 0.4.4
- Xcode: 10.2.1
- MacOS: 10.14.6
```

### Step to reproduce issue:

1. Using old version of pod (eg: `pod 'AFNetworking', '~> 3.0'`)
2. Run `pod install` to prebuild framework
3. Run `pod update AFNetworking` to update single pod
4. Check version of generated framework ==> Not updated

### Log
```
$ pod update AFNetworking --verbose --no-repo-update
  Preparing
    - Running pre install hooks
      - cocoapods-binary from `/Users/tuantm/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Main.rb`
🚀  Prebuild frameworks
        Preparing
          - Running pre install hooks
            - cocoapods-binary from `/Users/tuantm/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Main.rb`

Analyzing dependencies

Inspecting targets to integrate
        Using `ARCHS` setting to build architectures of target `Pods-cocoapods-binary-example`: (``)

Finding Podfile changes
        - AFNetworking

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
        M AFNetworking

Downloading dependencies

-> Installing AFNetworking 3.2.1 (was 3.1.0)
        > Copying AFNetworking from `/Users/tuantm/Library/Caches/CocoaPods/Pods/Release/AFNetworking/3.2.1-b6f89` to `Pods/_Prebuild/AFNetworking`
        - Running pre install hooks

Generating Pods project
        - Creating Pods project
        - Installing files into Pods project
          - Adding source files
          - Adding frameworks
          - Adding libraries
          - Adding resources
          - Linking headers
        - Installing Pod Targets
          - Installing target `AFNetworking` iOS 8.0
            - Generating module map file at `Pods/_Prebuild/Target Support Files/AFNetworking/AFNetworking.modulemap`
            - Generating umbrella header at `Pods/_Prebuild/Target Support Files/AFNetworking/AFNetworking-umbrella.h`
            - Generating Info.plist file at `Pods/_Prebuild/Target Support Files/AFNetworking/AFNetworking-Info.plist`
            - Generating dummy source at `Pods/_Prebuild/Target Support Files/AFNetworking/AFNetworking-dummy.m`
        - Installing Aggregate Targets
          - Installing target `Pods-cocoapods-binary-example` iOS 9.0
            - Generating Info.plist file at `Pods/_Prebuild/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-Info.plist`
            - Generating module map file at `Pods/_Prebuild/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example.modulemap`
            - Generating umbrella header at `Pods/_Prebuild/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-umbrella.h`
            - Generating dummy source at `Pods/_Prebuild/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-dummy.m`
        - Generating deterministic UUIDs
        - Stabilizing target UUIDs
        - Running post install hooks
        - Writing Xcode project file to `Pods/_Prebuild/Pods.xcodeproj`
        Cleaning up sandbox directory
        - Writing Lockfile in `Pods/_Prebuild/Manifest.lock.tmp`
        - Writing Manifest in `Pods/_Prebuild/Manifest.lock`
        - Running post install hooks
          - cocoapods-stats from `/Users/tuantm/.rvm/gems/ruby-2.6.3/gems/cocoapods-stats-1.1.0/lib/cocoapods_plugin.rb`

Sending stats
Prebuild frameworks (total 0)

🤖  Pod Install

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-cocoapods-binary-example`: (``)

Finding Podfile changes
  - AFNetworking

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  M AFNetworking

Downloading dependencies

-> Installing AFNetworking 3.2.1 (was 3.1.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Installing files into Pods project
    - Adding source files
    - Adding frameworks
    - Adding libraries
    - Adding resources
    - Linking headers
  - Installing Pod Targets
    - Installing target `AFNetworking` iOS 8.0
  - Installing Aggregate Targets
    - Installing target `Pods-cocoapods-binary-example` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-umbrella.h`
      - Generating dummy source at `Pods/Target Support Files/Pods-cocoapods-binary-example/Pods-cocoapods-binary-example-dummy.m`
  - Generating deterministic UUIDs
  - Stabilizing target UUIDs
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  Cleaning up sandbox directory
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-cocoapods-binary-example` (`cocoapods-binary-example.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Users/tuantm/.rvm/gems/ruby-2.6.3/gems/cocoapods-stats-1.1.0/lib/cocoapods_plugin.rb`

Sending stats

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by fedulvtubudul** [comment] 2019-09-23 04:59
I have same issue after trying to update one of the dependencies which has cp-binary enabled. The pod is specified with `git` and `tag` explicitly pointing to the new version. After doing no matter `pod install` or `pod update`, the log says `Installing MAGDebugKit 0.8.2 (was 0.8.1)`, like everything is OK, but it's really not. The workaround we've found is temporarily remove the dependency from  Podfile, run `pod install`, then return the dependency and repeat the `pod install` step.

**Comment by tuantm-citigo** [comment] 2019-09-26 04:35
@muzee-bot Did your project path contains space?

**Comment by kientux** [comment] 2019-10-25 07:33
I have the same problem too, and the workaround is temporary remove then reinstall the pods that updated, like @fedulvtubudul said.

**Comment by winstondu** [comment] 2020-06-28 02:21
This seems to be fixed by: https://github.com/leavez/cocoapods-binary/pull/104

**Closed** 2020-07-09 01:07 UTC
